.gitignore, dependency-analyzer-backend/pom.xml, dependency-analyzer-communication/pom.xml, dependency-analyzer-rest/pom.xml, pom.xml
Dependency analyzer empty project
=> [DA-1] Create empty project

backend/pom.xml, communication/pom.xml, pom.xml, rest/pom.xml
We discussed and decided to change groupids and artifactids
=> Change groupid and artifactid

.gitignore, pom.xml, reports-rest/pom.xml, reports-rest/src/main/java/org/jboss/da/reports/rest/model/GAVRequest.java, reports-rest/src/main/java/org/jboss/da/reports/rest/model/Product.java, reports-rest/src/main/java/org/jboss/da/reports/rest/model/Report.java, reports-rest/src/main/java/org/jboss/da/reports/rest/model/SCMRequest.java
As described on **REST endpoints proposal** page.
=> [DA-36] implement REST data model for DA reports

.gitignore, application/src/main/application/META-INF/jboss-deployment-structure.xml, common/pom.xml, common/src/main/java/org/jboss/da/common/json/DAConfig.java, common/src/main/java/org/jboss/da/common/util/Configuration.java, common/src/main/java/org/jboss/da/common/util/ConfigurationParseException.java, common/src/main/resources/da-config.json, common/src/test/java/org.jboss.da.common/json/DAConfigTest.java, common/src/test/resources/testConfig.json, communication/pom.xml, communication/src/main/java/org/jboss/da/communcation/pnc/PNC.java, communication/src/main/java/org/jboss/da/communcation/pnc/PNCProducer.java, communication/src/main/java/org/jboss/da/communcation/pnc/authentication/PNCAuthFilter.java, communication/src/main/java/org/jboss/da/communcation/pnc/authentication/PNCAuthentication.java, communication/src/main/java/org/jboss/da/communcation/pnc/entity/BuildConfiguration.java, communication/src/main/java/org/jboss/da/communcation/pnc/entity/BuildConfigurationSet.java, communication/src/main/java/org/jboss/da/communcation/pnc/entity/Product.java, communication/src/main/java/org/jboss/da/communcation/pnc/entity/Project.java, communication/src/test/java/org/jboss/da/communication/PNCTest.java, pom.xml
This is just a cleaned up PR with a single commit instead of several commits spread around as in #7.
=> Adding PNC interface for Dependency Analysis

pomanalyzer.sh
You need to have listings.sh in the same folder as pomanalyzer.sh
if you don't want to analyze transitive dependencies, use
pomanalyzer.sh --no-transitive
=> Add pomanalyzer script

listings.sh
Changed json parameters so they match new model
=> Update listings.sh so it points to service

pom.xml, testsuite/pom.xml, testsuite/src/test/java/org/jboss/da/test/AbstractArquillianTest.java, testsuite/src/test/java/org/jboss/da/test/TestOfTheTest.java, testsuite/src/test/resources/META-INF/application.xml
change packaging in createDeployment
remove creation of deployment from test classes
=> Fix testsuite

common/pom.xml, common/src/main/java/org/jboss/da/common/json/DAConfig.java, common/src/main/java/org/jboss/da/common/util/Configuration.java, communication/src/main/java/org/jboss/da/communication/pnc/PNC.java, communication/src/main/java/org/jboss/da/communication/pnc/api/PNCConnector.java, communication/src/main/java/org/jboss/da/communication/pnc/authentication/PNCAuthentication.java, communication/src/main/java/org/jboss/da/communication/pnc/impl/PNCConnectorImpl.java, communication/src/main/java/org/jboss/da/communication/pnc/model/BuildConfiguration.java, communication/src/main/java/org/jboss/da/communication/pnc/model/BuildConfigurationSet.java, communication/src/main/java/org/jboss/da/communication/pnc/model/Product.java, communication/src/main/java/org/jboss/da/communication/pnc/model/Project.java
Use lombok in common module and org.jboss.da.communication.pnc.model
Remove unnnecesary/wrong method call
Fix typo in communication package name
Refactor: Extract interface for PNC
Make PNCImpl @ApplicationScoped
Fix compiler warnings
Replace e.printStackTrace with throwing exception
=> Fixes for common and communication modules

common/src/main/java/org/jboss/da/common/json/DAConfig.java, common/src/main/resources/da-config.json, communication/pom.xml, communication/src/main/java/org/jboss/da/communcation/CommunicationException.java, communication/src/main/java/org/jboss/da/communication/aprox/api/AproxConnector.java, communication/src/main/java/org/jboss/da/communication/aprox/impl/AproxConnectorImpl.java, communication/src/main/java/org/jboss/da/communication/aprox/model/GA.java, communication/src/main/java/org/jboss/da/communication/aprox/model/VersionResponse.java, communication/src/main/java/org/jboss/da/communication/aprox/model/Versioning.java, communication/src/main/java/org/jboss/da/communication/aprox/model/Versions.java, reports-backend/src/main/java/org/jboss/da/reports/backend/impl/VersionFinderImpl.java, reports-backend/src/test/java/org/jboss/da/reports/backend/impl/VersionFinderTest.java, testsuite/pom.xml, testsuite/src/test/java/org/jboss/da/test/communication/AproxTest.java, testsuite/src/test/resources/META-INF/jboss-deployment-structure.xml
=> [DA-28] Implement AProx version finding

communication/pom.xml, communication/src/main/java/org/jboss/da/communication/model/GA.java, communication/src/main/java/org/jboss/da/communication/model/GAV.java, pom.xml, reports-backend/src/main/java/org/jboss/da/reports/backend/impl/VersionFinderImpl.java, reports-rest/pom.xml, reports-rest/src/main/java/org/jboss/da/rest/reports/model/LookupReport.java
Changed GAV/GA implementation so it is immutable and conforms with REST proposal.
Changed LooupReport so it conforms with REST proposal.
Added codehouse Jackson dependency in version that is in EAP 6.4
=> Fix some REST data implementation so it conforms with REST proposal

communication/src/main/java/org/jboss/da/communication/model/GAV.java, reports-rest/src/main/java/org/jboss/da/rest/listings/Artifacts.java, reports-rest/src/main/java/org/jboss/da/rest/reports/Reports.java
1. All the REST endpoint documentation will now show the HTTP status
code to expect
2. We can now see the expected JSON object/list we will receive from the
endpoint
3. A description of the parameters expected in the body of some requests
is provided.
=> [DA-89] Improvements to Swagger documentation

cli/da-cli-admin.sh, cli/da-cli.sh
1. Add new lines after each option
2. Add the expected output for pom-report option
=> Some tiny improvements to the "Usage"

communication/src/main/java/org/jboss/da/communication/model/GAV.java, reports-backend/src/main/java/org/jboss/da/reports/api/ArtifactReport.java, reports-rest/src/main/java/org/jboss/da/rest/reports/model/LookupReport.java
Swagger gets confused when generating the response class in its UI.
Those fixes will unconfuse swagger.
=> Some changes in models so that swagger does not get confused

common/pom.xml, common/src/main/java/org/jboss/da/common/util/Configuration.java, communication/pom.xml, communication/src/test/java/org/jboss/da/communication/model/GAVIntegrationTest.java, pom.xml, reports-rest/pom.xml, reports-rest/src/main/java/org/jboss/da/rest/reports/model/LookupReport.java
DA-117: pom.xml has dependencies on jackson deps with different versions
DA-118: /lookup/gav endpoint has duplicate groupid, artifactId, and version fields in the JSON reply
=> Fix for DA-117 and DA-118 for 0.2 branch

pom.xml, source-code-manager/pom.xml, source-code-manager/src/main/java/org/jboss/da/scm/SCM.java, source-code-manager/src/main/java/org/jboss/da/scm/SCMType.java, source-code-manager/src/test/java/org.jboss.da.scm.test/SCMTest.java
- Used Maven SCM library to achieve this.
Usage can be found by reading the `SCMTest` class.
=> [DA-113] Add module to clone a git or svn scm url

communication/src/main/java/org/jboss/da/communication/pnc/api/PNCConnector.java, communication/src/main/java/org/jboss/da/communication/pnc/impl/PNCConnectorImpl.java
DA-66 - Add 'Create Build Configuration Set' functionality to PNC communication
=> [DA-66] Add 'Create Build Configuration Set' functionality

reports-rest/src/main/java/org/jboss/da/rest/listings/Artifacts.java
Checking for artifact without parameters cause NullPointerException
=> [DA-143] Checking for artifact without parameters cause NPE

cli/listings.sh
=> Ensure mktemp works on OS X

bc-backend/src/main/java/org/jboss/da/bc/api/BuildConfigurationGenerator.java, bc-backend/src/main/java/org/jboss/da/bc/backend/api/BCSetGenerator.java, bc-backend/src/main/java/org/jboss/da/bc/backend/api/POMInfo.java, bc-backend/src/main/java/org/jboss/da/bc/backend/api/POMInfoGenerator.java, bc-backend/src/main/java/org/jboss/da/bc/backend/impl/BCSetGeneratorImpl.java, bc-backend/src/main/java/org/jboss/da/bc/backend/impl/POMInfoGeneratorImpl.java, bc-backend/src/main/java/org/jboss/da/bc/impl/BuildConfigurationGeneratorImpl.java, bc-backend/src/main/java/org/jboss/da/bc/model/GeneratorEntity.java, bc-backend/src/main/java/org/jboss/da/bc/model/ProjectDetail.java, bc-backend/src/main/java/org/jboss/da/bc/model/ProjectHiearchy.java, bc-backend/src/main/resources/META-INF/beans.xml, communication/src/main/java/org/jboss/da/communication/pom/PomAnalyzerImpl.java, communication/src/main/java/org/jboss/da/communication/scm/api/SCMConnector.java, communication/src/main/java/org/jboss/da/communication/scm/impl/SCMConnectorImpl.java, reports-backend/src/main/java/org/jboss/da/reports/backend/api/DependencyTreeGenerator.java, reports-backend/src/main/java/org/jboss/da/reports/backend/api/GAVToplevelDependencies.java, reports-backend/src/main/java/org/jboss/da/reports/backend/impl/DependencyTreeGeneratorImpl.java, reports-backend/src/main/java/org/jboss/da/reports/impl/ReportsGeneratorImpl.java, testsuite/src/test/java/org/jboss/da/test/server/communication/SCMRemoteTest.java
There is still one TODO in the code: https://github.com/project-ncl/dependency-analysis/pull/143/files#diff-7ace98b084b94613d03fb4155ed18d62R89
We must create Product in PNC somehow and obtain productId.
=> DA-109 Create backend engine for automated BC creation

cli-test/da-cli-test-helper.sh, cli-test/da-cli-test.sh, cli/listings.sh
Note: for some tests, we only test whether the cli outputs something,
since we cannot do direct string comparison of expected vs actual
output as the order that some dependencies appear always change.
=> [DA-142] Initial tests for cli

communication/src/main/java/org/jboss/da/communication/pom/PomAnalyzerImpl.java, communication/src/main/java/org/jboss/da/communication/pom/api/PomAnalyzer.java, communication/src/main/java/org/jboss/da/communication/scm/api/SCMConnector.java, communication/src/main/java/org/jboss/da/communication/scm/impl/SCMConnectorImpl.java
This is done by adding support for it in the `PomAnalyzer` class.
=> [DA-153] Implement getDependencyTreeOfRevision given a GAV

bc-backend/src/main/java/org/jboss/da/bc/impl/BuildConfigurationGeneratorImpl.java, reports-backend/src/main/java/org/jboss/da/reports/backend/api/DependencyTreeGenerator.java, reports-backend/src/main/java/org/jboss/da/reports/backend/impl/DependencyTreeGeneratorImpl.java
When dependencies are not found in AProx, try original repo of the
product.
=> BC generator: Search for dependencies in produc repo

bc-backend/src/main/java/org/jboss/da/bc/backend/impl/FinalizerImpl.java
When the existing BC was found, it was not used, but the application tried to create new one
=> Fix using existing BCs in BC generator

bc-rest/pom.xml, bc-rest/src/main/webapp/WEB-INF/web.xml, pom.xml, reports-rest/pom.xml, reports-rest/src/main/webapp/WEB-INF/web.xml
default value is /* you can specify own value with -Durl-pattern=value
=> [DA-168] Use property instead of hardcoded url in web.xml cors configuration

source-code-manager/src/main/java/org/jboss/da/scm/impl/SCMClonner.java, testsuite/src/test/java/org/jboss/da/test/server/scm/SCMTest.java
Otherwise fallback to the full git cloning.
=> [DA-158] Shallow clone git repositories when possible

bc-backend/src/main/java/org/jboss/da/bc/backend/impl/FinalizerImpl.java
Only removing created BuildConfigurations, as Product and Product
verion can't be deleted
=> [DA-163] If the finish process of Product import fails, rollback changes

bc-rest/src/main/webapp/doc/index.html, reports-rest/src/main/webapp/doc/index.html
As our service is behing firewall, the external validator can't see our json.
=> Disable swagger validator

bc-rest/src/main/java/org/jboss/da/bc/BuildConfigurationsREST.java, reports-rest/src/main/java/org/jboss/da/rest/listings/Artifacts.java, reports-rest/src/main/java/org/jboss/da/rest/reports/Reports.java, reports-rest/src/main/java/org/jboss/da/rest/repositories/Repositories.java
Respons for status 200 is taken from @ApiOperation, there should not be
@ApiResponse for for status 200.
Also added respons classes for other states than 200.
=> [DA-209] Remove @ApiResponse for status 200, add response for other states

cli/da-cli-admin.sh, cli/da-cli-script.py, cli/da-cli.sh, cli/listings.sh
Changes:
- We now have to specify the product for the whitelist
- As such, the CLI had to be changed to accomodate this change
- Instead of implementing the functionality in Bash, the author of the
commit decided to write part of it in Python since it's easier to
parse JSON in Python
This PR should be merged after PR #210
=> [DA-178] Add support for whitelist cli changes

common/src/main/java/org/jboss/da/common/json/DAConfig.java, common/src/main/resources/da-config.json, communication/src/main/java/org/jboss/da/communication/aprox/impl/AproxConnectorImpl.java
you need to change da-config according to document
https://docs.engineering.redhat.com/display/JP/Deployment+of+the+application+and+other+services
=> Change aprox config to use DA group

communication/src/main/java/org/jboss/da/communication/pom/PomAnalyzerImpl.java
There was an exception thrown, when pom version contained variable
=> Catch exception when there is wrong/weird pom file

cli/listings.sh, cli/pretty.py, reports-backend/src/main/java/org/jboss/da/listings/api/dao/ProductVersionDAO.java, reports-backend/src/main/java/org/jboss/da/listings/api/service/ArtifactService.java, reports-backend/src/main/java/org/jboss/da/listings/api/service/BlackArtifactService.java, reports-backend/src/main/java/org/jboss/da/listings/api/service/ProductVersionService.java, reports-backend/src/main/java/org/jboss/da/listings/impl/dao/ProductVersionDAOImpl.java, reports-backend/src/main/java/org/jboss/da/listings/impl/service/ArtifactServiceImpl.java, reports-backend/src/main/java/org/jboss/da/listings/impl/service/BlackArtifactServiceImpl.java, reports-backend/src/main/java/org/jboss/da/listings/impl/service/ProductVersionServiceImpl.java, reports-backend/src/main/java/org/jboss/da/listings/impl/service/WhiteArtifactServiceImpl.java, reports-backend/src/main/java/org/jboss/da/reports/api/AdvancedArtifactReport.java, reports-backend/src/main/java/org/jboss/da/reports/api/ArtifactReport.java, reports-backend/src/main/java/org/jboss/da/reports/impl/ReportsGeneratorImpl.java, reports-backend/src/test/java/org/jboss/da/reports/impl/ReportsGeneratorImplTest.java, reports-rest/src/main/java/org/jboss/da/rest/listings/Artifacts.java, reports-rest/src/main/java/org/jboss/da/rest/listings/model/RestGavProducts.java, reports-rest/src/main/java/org/jboss/da/rest/listings/model/RestProductInput.java, reports-rest/src/main/java/org/jboss/da/rest/reports/Reports.java, reports-rest/src/main/java/org/jboss/da/rest/reports/model/AdvancedReport.java, reports-rest/src/main/java/org/jboss/da/rest/reports/model/GAVAvailableVersions.java, reports-rest/src/main/java/org/jboss/da/rest/reports/model/GAVBestMatchVersion.java, reports-rest/src/main/java/org/jboss/da/rest/reports/model/LookupReport.java, reports-rest/src/main/java/org/jboss/da/rest/reports/model/Report.java, testsuite/src/test/rest/v-1.0/expectedResponse/reports/gav/guava18.json, testsuite/src/test/rest/v-1.0/expectedResponse/reports/gav/withDependencies.json, testsuite/src/test/rest/v-1.0/expectedResponse/reports/gav/withoutDependencies.json, testsuite/src/test/rest/v-1.0/expectedResponse/reports/lookup/gavs/guava13.json, testsuite/src/test/rest/v-1.0/expectedResponse/reports/lookup/gavs/guava13List.json, testsuite/src/test/rest/v-1.0/expectedResponse/reports/scm/dependency-analysis.json
Continue the implementation of PR #239
=> [DA-224] [master branch] Improve advanced reports

communication/src/main/java/org/jboss/da/communication/pnc/model/BuildConfigurationCreate.java, communication/src/main/java/org/jboss/da/communication/pnc/model/Environment.java, communication/src/main/java/org/jboss/da/communication/pnc/model/ProductMilestone.java, communication/src/main/java/org/jboss/da/communication/pnc/model/ProductRelease.java, communication/src/main/java/org/jboss/da/communication/pnc/model/ProductVersion.java, testsuite/src/test/java/org/jboss/da/test/server/communication/PncRemoteTest.java
PNC Rest API has changed a little bit for 0.8. This commit changes our
REST client for PNC to use the new PNC Rest API for 0.8.
Please merge **after** the next release!
=> [DA-194] Apply changes made in PNC REST API

reports-rest/src/main/java/org/jboss/da/rest/reports/Reports.java
This non-deterministic behaviour, where the test:
Test RestApiReportsRemoteTest::testGavLookupList
fails might be due to the fact that we are using a parallel stream to
concurrently add values to an ArrayList. However, an ArrayList is not
thread-safe by default and will probably suffer from a race condition,
since addition to the ArrayList is not synchronized.
So instead the ArrayList is replaced by a CopyOnWriteArrayList, which is
thread-safe.
=> [DA-202] Investigate why lookup test is non deterministic

cli/da-cli-script.py
The CLI will now try to capture HTTP request errors and print a nice
error message to the user, instead of crashing
=> [DA-221] CLI: better handle 5xx error

bc-backend/src/main/java/org/jboss/da/bc/impl/ProjectHiearchyCreator.java, bc-backend/src/main/java/org/jboss/da/bc/model/backend/ProjectDetail.java, bc-backend/src/test/java/org/jboss/da/bc/impl/ProjectHiearchyCreatorTest.java, bc-model/src/main/java/org/jboss/da/bc/model/rest/BuildConfiguration.java, bc-rest/src/main/java/org/jboss/da/bc/BuildConfigurationsREST.java, testsuite/src/test/rest/v-1.0/expectedResponse/build-configuration/generate/product/analyse-next-level/da-application-1.json
https://projects.engineering.redhat.com/browse/NCL-1884
=> Implemented NCL-1884

reports-backend/src/main/java/org/jboss/da/products/api/ArtifactDiff.java, reports-backend/src/main/java/org/jboss/da/products/api/ProductsService.java, reports-backend/src/main/java/org/jboss/da/products/impl/ProductsServiceImpl.java, reports-model/src/main/java/org/jboss/da/products/model/rest/GADiff.java, reports-model/src/main/java/org/jboss/da/products/model/rest/ProductDiff.java, reports-rest/src/main/java/org/jboss/da/rest/ReportsRestActivator.java, reports-rest/src/main/java/org/jboss/da/rest/products/Products.java, testsuite/src/test/java/org/jboss/da/test/client/AbstractRestApiTest.java, testsuite/src/test/java/org/jboss/da/test/client/rest/listings/AbstractRestApiListingTest.java, testsuite/src/test/java/org/jboss/da/test/client/rest/listings/RestApiListingsTest.java, testsuite/src/test/java/org/jboss/da/test/client/rest/products/RestApiProductsTest.java, testsuite/src/test/rest/v-1.0/expectedResponse/products/diff.json
=> [NCL-1888] Add endpoint for product diff

reports-backend/src/main/java/org/jboss/da/listings/api/service/WhiteArtifactFilterService.java, reports-backend/src/main/java/org/jboss/da/listings/api/service/WhiteArtifactService.java, reports-backend/src/main/java/org/jboss/da/listings/impl/service/BlackArtifactServiceImpl.java, reports-backend/src/main/java/org/jboss/da/listings/impl/service/WhiteArtifactFilterServiceImpl.java, reports-backend/src/main/java/org/jboss/da/listings/impl/service/WhiteArtifactServiceImpl.java, reports-rest/src/main/java/org/jboss/da/rest/listings/Artifacts.java, testsuite/pom.xml, testsuite/src/test/java/org/jboss/da/test/client/rest/listings/RestApiListingsTest.java, testsuite/src/test/java/org/jboss/da/test/server/ArtifactBlackWhitelistTransitionsTest.java
Implementation for https://projects.engineering.redhat.com/browse/NCL-1952 (more or less expanded version of NCL-1883).
=> Implementation for NCL-1952

.gitignore, README.md, application/pom.xml, pom.xml
- Added maven plugin/goal to deploy/undeploy
- Added info to readme about setup/run of project
=> Updated developer info in readme & added deploy plugin

bc-backend/src/main/java/org/jboss/da/bc/backend/api/BcChecker.java, bc-backend/src/main/java/org/jboss/da/bc/backend/impl/BcCheckerImpl.java, bc-backend/src/main/java/org/jboss/da/bc/backend/impl/FinalizerImpl.java, bc-backend/src/main/java/org/jboss/da/bc/impl/BuildConfigurationGeneratorImpl.java, bc-backend/src/main/java/org/jboss/da/bc/impl/ProjectHiearchyCreator.java, bc-backend/src/main/java/org/jboss/da/bc/model/backend/ProjectDetail.java, bc-backend/src/test/java/org/jboss/da/bc/backend/impl/BcCheckerImplTest.java, bc-model/src/main/java/org/jboss/da/bc/model/rest/BuildConfiguration.java, bc-rest/src/main/java/org/jboss/da/bc/facade/AbstractBuildConfigurationsFacade.java, testsuite/src/test/rest/v-1.0/expectedResponse/build-configuration/generate/product/analyse-next-level/da-application-1.json, testsuite/src/test/rest/v-1.0/expectedResponse/build-configuration/generate/product/analyse-next-level/da-common-1.json, testsuite/src/test/rest/v-1.0/expectedResponse/build-configuration/generate/product/start-process/da-common.json, testsuite/src/test/rest/v-1.0/expectedResponse/build-configuration/generate/product/start-process/da-parent.json, testsuite/src/test/rest/v-1.0/request/build-configuration/generate/product/analyse-next-level/da-application-1.json, testsuite/src/test/rest/v-1.0/request/build-configuration/generate/product/analyse-next-level/da-common-1.json, testsuite/src/test/rest/v-1.0/request/build-configuration/generate/product/finish-process/da-parent.json
.. instead of just using the first one.
https://projects.engineering.redhat.com/browse/NCL-2102
=> NCL-2102: Use all existing Build Configs from PNC 

communication/src/main/java/org/jboss/da/communication/pnc/model/BuildConfigurationCreate.java, testsuite/src/test/rest/v-1.0/expectedResponse/reports/align/dependency-analysis.json
Fixing /report/align/dependency-analysis.json
=> Minor fix to testsuite JSON reply

bc-backend/src/main/java/org/jboss/da/bc/backend/impl/FinalizerImpl.java
Current workflow doesn't count on repo cloning
=> Disable repo cloning

testsuite/src/test/java/org/jboss/da/test/server/scm/SCMTest.java
https://projects.engineering.redhat.com/browse/NCL-1921
=> Test case to clarify git clone over ssh, refactored SCMTest

reports-rest/src/main/java/org/jboss/da/rest/facade/ReportsFacade.java, reports-rest/src/main/java/org/jboss/da/rest/reports/Reports.java, reports-rest/src/main/java/org/jboss/da/rest/ws/ReportsMethodsImpl.java
=> [NCL-2662] Add Websocket variants of DA reports

cli-wrap/src/main/resources/cli/da-cli.py, cli-wrap/src/main/resources/cli/da_cli_script.py, cli-wrap/src/main/resources/cli/listings.py, cli-wrap/src/main/resources/cli/pretty.py, cli-wrap/src/main/resources/cli/test.sh, cli-wrap/src/main/resources/cli/testsuite.py
=> [NCL-2666] Switch DA CLI to websocket endpoints for reports

communication/src/main/java/org/jboss/da/communication/aprox/impl/AproxConnectorImpl.java
This commit also adds a retry for HTTP status 500 from Indy when
fetching the maven-metadata.xml file. This is in addition to the current
logic which is to retry on HTTP status 504.
This is done as Indy sometimes recovers from HTTP status 500 errors to
provide us with the right content (See NOS-1155).
This commit also adds a waiting time between retries; with the waiting
time determined by using an exponential backoff. This will hopefully
help the network/Indy recover from overload and provide the correct data
at a later time.
=> [NCL-3604] Add retry for status 500 from Indy

README.md, application/pom.xml, application/src/main/application/META-INF/application.xml, application/src/main/application/META-INF/jboss-deployment-structure.xml, communication/pom.xml, communication/src/main/java/org/jboss/da/communication/aprox/impl/AproxConnectorImpl.java, communication/src/test/java/org/jboss/da/communication/aprox/AproxConnectorTest.java, metrics/pom.xml, metrics/src/main/java/org/jboss/da/metrics/MetricsConfiguration.java, metrics/src/main/java/org/jboss/da/metrics/exceptions/NoPropertyException.java, pom.xml, reports-rest/pom.xml, reports-rest/src/main/java/org/jboss/da/rest/ReportsRestActivator.java, reports-rest/src/main/java/org/jboss/da/rest/metrics/GeneralRestMetricsFilter.java, reports-rest/src/main/java/org/jboss/da/rest/metrics/TimedMetric.java, reports-rest/src/main/java/org/jboss/da/rest/metrics/TimedMetricFilter.java, testsuite/pom.xml, testsuite/src/test/resources/META-INF/application.xml, testsuite/src/test/resources/META-INF/jboss-deployment-structure.xml
This PR adds:
- Metrics support via Dropwizard Metrics for JVM and in-app instrumentation
- Add all REST req/s and timer
- Add support to instrument particular REST method via `@TimedMetric`
- Add timer for Apox/Indy client
=> [v1.3] Add metrics support

reports-backend/src/main/java/org/jboss/da/products/impl/AggregatedProductProvider.java
The conversion sometimes failed with "RejectedExecutionException:
Thread limit exceeded replacing blocked worker" because it used default
fork-join-pool that could spawn a big number of threads theat were just
waiting.
Now we use small amount of threads in ScheduledExecutor to periodically
check whether the Future completed or not.
=> [NCL-4024] Fix conversion of Future to CompletableFuture

CHANGELOG.md, reports-rest/src/main/webapp/WEB-INF/web.xml, testsuite/src/test/replacements/reports-rest/WEB-INF/web.xml
=> [NCL-4236] Allow any authenticated user to do stuff

reports-rest/src/main/webapp/WEB-INF/web.xml, testsuite/src/test/replacements/reports-rest/WEB-INF/web.xml
=> [v1.4][NCL-4236] Allow any authenticated user to do stuff

common/src/main/java/org/jboss/da/common/version/SuffixedVersion.java, common/src/test/java/org/jboss/da/common/version/VersionAnalyzerTest.java, common/src/test/java/org/jboss/da/common/version/VersionComparatorTest.java
I'll update CHANGELOG.md after the merge
=> [NCL-4532] with the same Versions, prefer OSGi format

reports-rest/src/main/java/org/jboss/da/rest/metrics/TimedMetricFilter.java
=> NCL-4972 - Add metric to track errors in rest endpoints

reports-backend/src/main/java/org/jboss/da/listings/impl/service/BlackArtifactServiceImpl.java, testsuite/src/test/java/org/jboss/da/test/client/rest/listings/BugReporoducerRemoteTest.java, testsuite/src/test/resources/wiremock/__files/body-jboss-parent.xml, testsuite/src/test/resources/wiremock/mappings/mapping-jboss-parent.json, testsuite/src/test/rest/v-1/expectedResponse/reports/lookup/gavs/ncl5035.json, testsuite/src/test/rest/v-1/request/listings/gavParent.json, testsuite/src/test/rest/v-1/request/reports/lookup/gavs/ncl5035.json
=> Fix wrong detecting of blacklisted non-osgi versions

reports-rest/src/main/java/org/jboss/da/rest/metrics/GeneralRestMetricsFilter.java, reports-rest/src/main/java/org/jboss/da/rest/metrics/TimedMetricFilter.java
=> [1.7] NCL-4972 - Add metric to track errors in rest endpoints

common/src/main/java/org/jboss/da/common/util/LoggerProducer.java, common/src/main/java/org/jboss/da/common/util/UserLog.java, communication/src/main/java/org/jboss/da/communication/aprox/impl/AproxConnectorImpl.java, communication/src/test/java/org/jboss/da/communication/aprox/AproxConnectorTest.java, reports-backend/src/main/java/org/jboss/da/products/impl/RepositoryProductProvider.java, reports-backend/src/main/java/org/jboss/da/reports/impl/ReportsGeneratorImpl.java, reports-backend/src/test/java/org/jboss/da/reports/impl/ReportsGeneratorImplTest.java
=> [NCL-5010] Add user related logs

common/src/main/java/org/jboss/da/common/logging/MDCUtils.java, communication/src/main/java/org/jboss/da/communication/aprox/impl/AproxConnectorImpl.java, reports-rest/src/main/java/org/jboss/da/rest/ReportsRestActivator.java, reports-rest/src/main/java/org/jboss/da/rest/filter/MDCLoggingFilter.java
=> [NCL-5069] Pass log context in headers

common/src/main/java/org/jboss/da/common/version/VersionParser.java, common/src/test/java/org/jboss/da/common/version/VersionAnalyzerTest.java, testsuite/src/test/java/org/jboss/da/test/client/rest/reports/BugReporoducerRemoteTest.java, testsuite/src/test/resources/wiremock/__files/body-jansi-maven-metadata.xml-2ADql.xml, testsuite/src/test/rest/v-1/expectedResponse/reports/lookup/gavs/ncl5035_1.json, testsuite/src/test/rest/v-1/request/reports/lookup/gavs/NCL5377.json
=> [NCL-5391] understand dot and comma characters in nonOSGi qualifiers

common/src/main/java/org/jboss/da/common/json/DefaultModuleGroup.java, common/src/main/java/org/jboss/da/common/version/VersionAnalyzer.java, common/src/test/java/org/jboss/da/common/version/VersionComparatorTest.java, communication/src/main/java/org/jboss/da/communication/aprox/api/AproxConnector.java, communication/src/main/java/org/jboss/da/communication/aprox/impl/AproxConnectorImpl.java, communication/src/main/java/org/jboss/da/communication/pom/GalleyWrapper.java, communication/src/main/java/org/jboss/da/communication/pom/api/PomAnalyzer.java, communication/src/main/java/org/jboss/da/communication/pom/qualifier/DACartographerCore.java, eclipse-codeStyle.xml, reports-backend/src/main/java/org/jboss/da/listings/api/dao/GenericDAO.java, reports-backend/src/main/java/org/jboss/da/listings/api/dao/ProductVersionDAO.java, reports-backend/src/main/java/org/jboss/da/listings/api/service/BlackArtifactService.java, reports-backend/src/main/java/org/jboss/da/listings/api/service/ProductVersionService.java, reports-backend/src/main/java/org/jboss/da/listings/api/service/WhiteArtifactFilterService.java, reports-backend/src/main/java/org/jboss/da/listings/api/service/WhiteArtifactService.java, reports-backend/src/main/java/org/jboss/da/products/api/Artifact.java, reports-backend/src/main/java/org/jboss/da/products/api/ProductProvider.java, reports-backend/src/main/java/org/jboss/da/products/impl/AggregatedProductProvider.java, reports-backend/src/main/java/org/jboss/da/reports/api/ReportsGenerator.java, reports-model/src/main/java/org/jboss/da/model/rest/validators/ScmUrlValidator.java, source-code-manager/src/main/java/org/jboss/da/scm/api/SCM.java, source-code-manager/src/main/java/org/jboss/da/scm/api/SCMType.java, source-code-manager/src/main/java/org/jboss/da/scm/impl/DirectoryReference.java, source-code-manager/src/main/java/org/jboss/da/scm/impl/ScmFacade.java, testsuite/src/test/java/org/jboss/da/test/ArquillianDeploymentFactory.java
=> [NCL-1810] 120 length line comment

pom.xml
=> Set up maven-release plugin

pom.xml
=> [NCL-5725] move nexus staging repo to last place

pom.xml
=> Add tagSuffix to enable automatic RC releases

reports-model/src/main/java/org/jboss/da/model/rest/GA.java, reports-model/src/test/java/org/jboss/da/model/rest/GAVTest.java
=> [NCL-5774] Allow groupid parts starting with number

cli-wrap/src/main/resources/cli/da-cli.py, reports-rest/src/main/java/org/jboss/da/rest/reports/Reports.java, reports-rest/src/main/java/org/jboss/da/rest/ws/ReportsMethodsImpl.java, testsuite/src/test/java/org/jboss/da/test/client/rest/reports/RestApiReportsRemoteTest.java
=> [NCL-5827] Remove GAV report endpoints

common/src/main/java/org/jboss/da/common/json/GlobalConfig.java, common/src/test/resources/testConfig.json
=> [NCL-6014] Make sure that Indy URL doesn't have double slash

common/src/main/java/org/jboss/da/common/version/VersionParser.java, reports-backend/src/main/java/org/jboss/da/products/api/ProductProvider.java, reports-backend/src/main/java/org/jboss/da/products/impl/AggregatedProductProvider.java, reports-backend/src/main/java/org/jboss/da/products/impl/DatabaseProductProvider.java, reports-backend/src/main/java/org/jboss/da/products/impl/RepositoryProductProvider.java, reports-backend/src/main/java/org/jboss/da/reports/api/ReportsGenerator.java, reports-backend/src/main/java/org/jboss/da/reports/impl/ReportsGeneratorImpl.java, reports-model/src/main/java/org/jboss/da/reports/model/request/VersionsNPMRequest.java, reports-model/src/main/java/org/jboss/da/reports/model/response/NPMVersionsReport.java, reports-rest/src/main/java/org/jboss/da/rest/facade/ReportsFacade.java, reports-rest/src/main/java/org/jboss/da/rest/reports/Reports.java, testsuite/src/test/java/org/jboss/da/test/client/rest/reports/RestApiReportsRemoteTest.java, testsuite/src/test/java/org/jboss/da/test/server/communication/AproxRemoteTest.java, testsuite/src/test/resources/wiremock/__files/body-jquery-package.json-vDrxC.json, testsuite/src/test/rest/v-1/expectedResponse/reports/versions/npm/jquery151.json, testsuite/src/test/rest/v-1/request/reports/versions/npm/jquery151.json
=> [NCL-5946] Add NPM version find&filter endpoint

pom.xml, testsuite/pom.xml, testsuite/src/test/java/org/jboss/da/test/client/rest/RestApiIndexTestIT.java, testsuite/src/test/java/org/jboss/da/test/client/rest/listings/BugReporoducerRemoteTestIT.java, testsuite/src/test/java/org/jboss/da/test/client/rest/listings/RestApiListingsTestIT.java, testsuite/src/test/java/org/jboss/da/test/client/rest/products/RestApiProductsTestIT.java, testsuite/src/test/java/org/jboss/da/test/client/rest/reports/AlignRemoteTestIT.java, testsuite/src/test/java/org/jboss/da/test/client/rest/reports/BugReporoducerRemoteTestIT.java, testsuite/src/test/java/org/jboss/da/test/client/rest/reports/RestApiReportsRemoteTestIT.java, testsuite/src/test/java/org/jboss/da/test/client/ws/reports/WebsocketApiReportsTestIT.java, testsuite/src/test/java/org/jboss/da/test/server/ArtifactBlackWhitelistTransitionsTestIT.java, testsuite/src/test/java/org/jboss/da/test/server/DeploymentTestIT.java, testsuite/src/test/java/org/jboss/da/test/server/ReportsWithWhitelistedArtifactsRemoteTestIT.java, testsuite/src/test/java/org/jboss/da/test/server/communication/AproxRemoteTestIT.java, testsuite/src/test/java/org/jboss/da/test/server/communication/GAVComparatorRemoteTestIT.java, testsuite/src/test/java/org/jboss/da/test/server/communication/GalleyWrapperTestIT.java, testsuite/src/test/java/org/jboss/da/test/server/communication/SCMRemoteTestIT.java, testsuite/src/test/java/org/jboss/da/test/server/listings/WhiteArtifactServiceTestIT.java, testsuite/src/test/java/org/jboss/da/test/server/scm/SCMTestIT.java
=> [NCL-6030] Remove testsuite activation by profile

communication/pom.xml, source-code-manager/pom.xml
=> Make DA compilable on java 11

README.md, common/src/main/java/org/jboss/da/common/CommunicationException.java
CommunicationException
+ forgotten readme update.
=> Improve error message when cause.message is null for

reports-model/src/main/java/org/jboss/da/lookup/model/MavenLatestRequest.java, reports-model/src/main/java/org/jboss/da/lookup/model/MavenLatestResult.java, reports-model/src/main/java/org/jboss/da/lookup/model/MavenLookupRequest.java, reports-model/src/main/java/org/jboss/da/lookup/model/MavenLookupResult.java, reports-model/src/main/java/org/jboss/da/lookup/model/NPMLookupRequest.java, reports-model/src/main/java/org/jboss/da/lookup/model/NPMLookupResult.java, reports-model/src/main/java/org/jboss/da/reports/model/request/VersionsNPMRequest.java, reports-model/src/test/java/org/jboss/da/reports/model/response/DeserializationTest.java, reports-model/src/test/resources/deserializeTest/versionsNPMRequest.json, reports-rest/src/main/java/org/jboss/da/rest/LookupImpl.java, reports-rest/src/main/java/org/jboss/da/rest/api/Lookup.java
=> New API for geting latest version

common/src/main/java/org/jboss/da/common/json/LookupMode.java, common/src/main/resources/da-config.json, common/src/test/java/org/jboss/da/common/util/ConfigurationTest.java, reports-backend/src/main/java/org/jboss/da/reports/api/LookupGenerator.java, reports-backend/src/main/java/org/jboss/da/reports/impl/LookupGeneratorImpl.java, reports-backend/src/main/java/org/jboss/da/reports/impl/ReportsGeneratorImpl.java, reports-rest/src/main/java/org/jboss/da/rest/LookupImpl.java, testsuite/src/test/java/org/jboss/da/test/client/rest/lookup/LookupTestIT.java, testsuite/src/test/java/org/jboss/da/test/client/rest/reports/RestApiReportsRemoteTestIT.java, testsuite/src/test/resources/wiremock/__files/body-pnc-jquery151-1g.json, testsuite/src/test/resources/wiremock/mappings/mapping-pnc-jquery151-1g.json, testsuite/src/test/resources/wiremock/mappings/pnc-rest-guava-all-versions.json, testsuite/src/test/rest/v-1/expectedResponse/lookup/maven/latest/guava13Temp.json, testsuite/src/test/rest/v-1/expectedResponse/lookup/maven/latest/guava13Temp2.json, testsuite/src/test/rest/v-1/expectedResponse/reports/versions/npm/jquery151-2.json, testsuite/src/test/rest/v-1/request/lookup/maven/latest/guava13Temp.json, testsuite/src/test/rest/v-1/request/lookup/maven/latest/guava13Temp2.json, testsuite/src/test/rest/v-1/request/reports/versions/npm/jquery151-2.json
=> Latest version

.gitignore, common/src/main/java/org/jboss/da/common/json/DAConfig.java, common/src/main/resources/da-config.json, communication/src/main/java/org/jboss/da/communication/indy/impl/IndyConnectorImpl.java
=> [NCL-6477] - Extract the number of retries when querying Indy to make it configurable

communication/src/main/java/org/jboss/da/communication/pnc/PncConnectorImpl.java
=> Use null port when no port is in PNC url

reports-model/src/main/java/org/jboss/da/reports/model/response/AdvancedReport.java, reports-model/src/main/java/org/jboss/da/reports/model/response/NPMVersionsReport.java, reports-model/src/main/java/org/jboss/da/reports/model/response/Report.java
=> Rest model changes in reports entities required for bacon usage

reports-model/src/main/java/org/jboss/da/reports/model/response/striped/AdvancedReport.java, reports-model/src/main/java/org/jboss/da/reports/model/response/striped/AlignReport.java, reports-model/src/main/java/org/jboss/da/reports/model/response/striped/AlignReportModule.java, reports-model/src/main/java/org/jboss/da/reports/model/response/striped/AlignReportModuleWithDiff.java, reports-model/src/main/java/org/jboss/da/reports/model/response/striped/GAVAvailableVersionsWithDiff.java, reports-model/src/main/java/org/jboss/da/reports/model/response/striped/Report.java, reports-model/src/main/java/org/jboss/da/reports/model/response/striped/RestVersionProduct.java, reports-model/src/main/java/org/jboss/da/reports/model/response/striped/VersionWithDifference.java, reports-model/src/main/java/org/jboss/da/reports/model/response/striped/WLStripper.java
=> Add WLStripper to strip whitelist info from payloads

communication/pom.xml, pom.xml, testsuite/pom.xml
=> Update to J11 Compiler

common/pom.xml, common/src/main/java/org/jboss/da/common/auth/AuthenticatorService.java, common/src/main/java/org/jboss/da/common/auth/impl/JAASAuthenticatorService.java, common/src/main/java/org/jboss/da/common/auth/impl/KeycloakAuthenticatorService.java, common/src/main/java/org/jboss/da/common/logging/AppLifecycle.java, common/src/main/java/org/jboss/da/common/logging/AuditLogger.java, communication/pom.xml, reports-backend/src/main/java/org/jboss/da/listings/api/model/Artifact.java, reports-backend/src/main/java/org/jboss/da/listings/impl/dao/BlackArtifactDAOImpl.java, reports-backend/src/main/java/org/jboss/da/listings/impl/dao/GenericDAOImpl.java, reports-backend/src/main/java/org/jboss/da/listings/impl/dao/WhiteArtifactDAOImpl.java, reports-backend/src/main/java/org/jboss/da/listings/impl/service/ArtifactServiceImpl.java, reports-rest/src/main/java/org/jboss/da/rest/filter/MDCLoggingFilter.java, reports-rest/src/main/java/org/jboss/da/rest/ws/ReportsEndpoint.java, testsuite/src/test/java/org/jboss/da/test/server/ArtifactBlackWhitelistTransitionsTestIT.java, testsuite/src/test/java/org/jboss/da/test/server/ReportsWithWhitelistedArtifactsRemoteTestIT.java, testsuite/src/test/java/org/jboss/da/test/server/listings/WhiteArtifactServiceTestIT.java, testsuite/src/test/replacements/communication/META-INF/beans.xml, testsuite/src/test/replacements/reports-backend/META-INF/beans.xml, testsuite/src/test/replacements/reports-rest/WEB-INF/beans.xml
=> [NCL-7304] Add audit logging of events of interests

common/pom.xml, common/src/main/java/org/jboss/da/common/version/VersionAnalyzer.java, common/src/main/java/org/jboss/da/common/version/VersionComparator.java, reports-backend/src/main/java/org/jboss/da/reports/api/LookupGenerator.java, reports-backend/src/main/java/org/jboss/da/reports/impl/LookupGeneratorImpl.java, reports-model/src/main/java/org/jboss/da/lookup/model/MavenVersionsRequest.java, reports-model/src/main/java/org/jboss/da/lookup/model/MavenVersionsResult.java, reports-model/src/main/java/org/jboss/da/lookup/model/NPMVersionsRequest.java, reports-model/src/main/java/org/jboss/da/lookup/model/NPMVersionsResult.java, reports-model/src/main/java/org/jboss/da/lookup/model/VersionFilter.java, reports-rest/src/main/java/org/jboss/da/rest/LookupImpl.java, reports-rest/src/main/java/org/jboss/da/rest/api/Lookup.java, testsuite/src/test/java/org/jboss/da/test/client/rest/lookup/LookupTestIT.java, testsuite/src/test/rest/v-1/expectedResponse/lookup/maven/versions/guava13.json, testsuite/src/test/rest/v-1/expectedResponse/lookup/maven/versions/guava13Minor.json, testsuite/src/test/rest/v-1/expectedResponse/lookup/npm/versions/jquery151.json, testsuite/src/test/rest/v-1/expectedResponse/lookup/npm/versions/jquery151Major.json, testsuite/src/test/rest/v-1/request/lookup/maven/versions/guava13.json, testsuite/src/test/rest/v-1/request/lookup/maven/versions/guava13Minor.json, testsuite/src/test/rest/v-1/request/lookup/npm/versions/jquery151.json, testsuite/src/test/rest/v-1/request/lookup/npm/versions/jquery151Major.json
=> [NCL-7184] Intoduce endpoint for avalable versions lookup

reports-rest/src/main/java/org/jboss/da/rest/LookupImpl.java, reports-rest/src/main/java/org/jboss/da/rest/listings/BlackListImpl.java
=> [NCL-7335] Remove annotation which creates a duplicated span

pom.xml, reports-rest/src/main/java/org/jboss/da/rest/filter/MDCLoggingFilter.java
=> NCL-7335 - Use new utility class to set MDC values from OTEL headers

common/src/main/java/org/jboss/da/common/version/VersionAnalyzer.java, common/src/main/java/org/jboss/da/common/version/VersionComparator.java, common/src/test/java/org/jboss/da/common/version/VersionComparatorTest.java, reports-backend/src/main/java/org/jboss/da/reports/api/LookupGenerator.java, reports-backend/src/main/java/org/jboss/da/reports/impl/LookupGeneratorImpl.java, reports-model/src/main/java/org/jboss/da/lookup/model/MavenVersionsRequest.java, reports-model/src/main/java/org/jboss/da/lookup/model/NPMVersionsRequest.java, reports-model/src/main/java/org/jboss/da/lookup/model/VersionDistanceRule.java, reports-rest/src/main/java/org/jboss/da/rest/LookupImpl.java, testsuite/src/test/java/org/jboss/da/test/client/rest/lookup/LookupTestIT.java, testsuite/src/test/rest/v-1/expectedResponse/lookup/maven/versions/guava13Closest.json, testsuite/src/test/rest/v-1/request/lookup/maven/versions/guava13Closest.json
=> new ordering of available versions

communication/src/main/java/org/jboss/da/communication/pnc/PncConnectorImpl.java, pom.xml
=> feat(*): update pnc version to expose new build category

pom.xml
=> Update otel instrumentation to 1.22.0

common/src/main/java/org/jboss/da/common/version/VersionComparator.java, common/src/test/java/org/jboss/da/common/version/VersionComparatorTest.java
=> [NCLSUP-898] Fix wrong ordering of lesser versions in CLOSEST_BY_PARTS

common/src/main/java/org/jboss/da/common/ScopedGAVStrategy.java, common/src/main/java/org/jboss/da/common/ScopedStrategy.java, common/src/main/java/org/jboss/da/common/version/VersionAnalyzer.java, common/src/main/java/org/jboss/da/common/version/VersionStrategy.java, common/src/test/java/org/jboss/da/common/version/VersionAnalyzerTest.java, reports-backend/src/main/java/org/jboss/da/reports/impl/LookupGeneratorImpl.java
=> [NCL-7877] decouple version functionality from ScopedStrategy

application/pom.xml, cli-wrap/pom.xml, common/pom.xml, communication/pom.xml, pom.xml, reports-backend/pom.xml, reports-model/pom.xml, reports-rest/pom.xml, source-code-manager/pom.xml, testsuite/pom.xml
=> Next is 2.6

common/pom.xml, common/src/main/templates/org/jboss/da/common/Constants.java, pom.xml, reports-rest/src/main/java/org/jboss/da/rest/VersionEndpointImpl.java, reports-rest/src/main/java/org/jboss/da/rest/api/VersionEndpoint.java
=> [NCL-6708] Add /rest/v-1/version endpoint

reports-rest/src/main/java/org/jboss/da/rest/ReportsRestActivator.java
=> [NCL-6708] Activate version endpoint

reports-rest/src/main/webapp/WEB-INF/web.xml
The role name is: pnc-users-da-admin
=> [NCL-8155] Require role to blocklist artifact

reports-rest/src/main/webapp/WEB-INF/web.xml
The role name is: pnc-users-da-admin
=> [v2.6.x][NCL-8155] Require role to blocklist artifact

pom.xml
=> Bump RHSSO version from 7.6.1 to 7.6.5

reports-rest/src/main/webapp/WEB-INF/web.xml
This reverts commit 9069cbfa9494ed3608a21f8bbf497811eebd9f16.
=> Revert "[NCL-8155] Require role to blocklist artifact"

reports-rest/src/main/webapp/WEB-INF/web.xml
=> [NCL-8147] Rename role needed for add/delete blacklisted builds

reports-rest/src/main/java/org/jboss/da/rest/JacksonProvider.java, reports-rest/src/main/java/org/jboss/da/rest/ReportsRestActivator.java
=> [NCL-6708] Activate JacksonProvider provider

reports-backend/src/main/java/org/jboss/da/listings/api/dao/ArtifactDAO.java, reports-backend/src/main/java/org/jboss/da/listings/api/dao/GADAO.java, reports-backend/src/main/java/org/jboss/da/listings/api/model/Artifact.java, reports-backend/src/main/java/org/jboss/da/listings/api/service/BlackArtifactService.java, reports-backend/src/main/java/org/jboss/da/listings/impl/dao/ArtifactDAOImpl.java, reports-backend/src/main/java/org/jboss/da/listings/impl/dao/GADAOImpl.java, reports-backend/src/main/java/org/jboss/da/listings/impl/service/BlackArtifactServiceImpl.java, reports-backend/src/main/java/org/jboss/da/reports/impl/LookupGeneratorImpl.java
We will now prefetch all relevant blocklisted GAVs to in memory cahce and then query the cache.
=> [NCLSUP-1016] Optimize blocklist querying

reports-backend/src/main/java/org/jboss/da/listings/impl/dao/ArtifactDAOImpl.java, testsuite/src/test/java/org/jboss/da/test/client/rest/listings/AbstractRestApiListingTest.java, testsuite/src/test/java/org/jboss/da/test/client/rest/lookup/LookupTestIT.java, testsuite/src/test/java/org/jboss/da/test/client/rest/lookup/LookupTestITBlocklist.java, testsuite/src/test/rest/v-1/expectedResponse/lookup/maven/guava13Blocklist.json, testsuite/src/test/rest/v-1/request/lookup/maven/guava13Blocklist.json
=> Fix double in

reports-rest/src/main/webapp/WEB-INF/web.xml
=> [v2.6.x] Bring roles back

reports-rest/src/main/java/org/jboss/da/rest/ReportsRestActivator.java
=> [v2.6.x][NCL-6708] Activate JacksonProvider provider

application/pom.xml, cli-wrap/pom.xml, common/pom.xml, communication/pom.xml, pom.xml, reports-backend/pom.xml, reports-model/pom.xml, reports-rest/pom.xml, source-code-manager/pom.xml, testsuite/pom.xml
=> Migrate to Central Publisher
