project-ncl/dependency-analysis

listings.sh

Usage:
``./listings.sh add (b[lack]|w[hite]) GROUP_ID:ARTIFACT_ID:VERSION`` - Add new artifact to black/white list
``./listings.sh check (b[lack]|w[hite]) GROUP_ID:ARTIFACT_ID:VERSION`` - Check if artifact is in black/white list
``./listings.sh list (b[lack]|w[hite])`` - Print out all artifact in black/white list

add CLI tool for Black&White listings

---

reports-rest/README.md
reports-rest/src/main/java/org/jboss/da/rest/ReportsRestActivator.java
reports-rest/src/main/java/org/jboss/da/rest/reports/Reports.java

Refactored a little bit `ReportsRestActivator.java` so that it's easier to add new JAX-RS classes to the set of classes.
Also added the `Reports.class` class to the set of classes, so that the JAX-RS endpoint `/reports` is activated.

Activate Reports JAX-RS class

---

communication/src/main/java/org/jboss/da/communication/aprox/model/GA.java
communication/src/main/java/org/jboss/da/communication/aprox/model/GAV.java

The unmarshalling error occured because the `GAV` class has a default
constructor that requires arguments.
Jackson requires the Java POJOs to have a 'no arguments' constructor to be
able to match the JSON structure to a JAVA POJO (https://github.com/FasterXML/jackson-annotations#using-constructors-or-factory-methods). Since the `GAV`
class previously had **no** 'no arguments' constructor, the matching failed.
By adding the `@NoArgsConstructor` to the `GAV` class, a 'no arguments'
constructor is created, which makes Jackson happy.
No tests are provided for this commit. However in the future integration
tests will be added to those REST endpoints to catch these kinds of
errors.
The commit was verified manually using the Swagger UI [[http://localhost:8080/reports-rest/swagger-ui/#!/reports/lo …

Fix the unmarshalling error in the reports-rest '/lookup/gav' endpoint

---

reports-rest/src/main/java/org/jboss/da/rest/reports/model/LookupReport.java

Currently, the lombok annotations prevent the `bestMatchVersion` field to be null. This PR changes that behavior so that we can return `null` as JSON value to the key `bestMatchVersion`, instead of getting a `NullPointerException`
JIRA: DA-82, DA-75, DA-76

Allow `bestMatchVersion` to be null

---

common/src/main/java/org/jboss/da/common/json/DAConfig.java
common/src/main/resources/da-config.json
communication/src/main/java/org/jboss/da/communication/aprox/impl/AproxConnectorImpl.java
testsuite/src/test/java/org/jboss/da/test/communication/AproxTest.java

We have decided to use the Aprox remote feature instead of the Aprox
group feature for now. Later on we might go back to the group feature.
Note: the da-config.json structure was changed as a result of this change. Please consult the deployment document for the new values.
DA-81

Move from Aprox group to Aprox remote

---

reports-backend/src/main/java/org/jboss/da/reports/backend/impl/VersionFinderImpl.java
reports-backend/src/test/java/org/jboss/da/reports/backend/impl/VersionFinderTest.java

DA-86, DA-88
This PR includes the commit of @janinko for `VersionFinderTest` (#59)
Some minor changes were made to that commit (See 00472bc). The maven formatter plugin has also reformatted the `VersionFinderTest` class, which explains the non-code diffs introduced in 00472bc.
By fixing those tests [DA-86], this PR also accidentally fixes DA-88.

[DA-86][DA-88] fix `VersionFinderImpl`

---

reports-backend/src/main/java/org/jboss/da/reports/api/ArtifactReport.java
reports-backend/src/test/java/org/jboss/da/reports/impl/TestReportsGenerator.java

This situation occurs if the `bestMatchVersion` is also null. This
occurs when no best match is found.
Previously even if the best match was null, it was also added to the
available versions when calling `setBestMatchVersion` in `ArtifactReport`.
This commit now checks if the best match is *not null* before adding it to
the set of available versions. It still allows `bestMatchVersion` to be
set to null though, since we might have legitimate reasons to set
`bestMatchVersion` to null.
The unit test basically sets the `bestMatchVersion` to null, and we scan
the versions in `getAvailableVersions()` to make sure that no element in
the set is null.

[DA-87] bug fix: available versions in report contains null

---

reports-backend/src/main/java/org/jboss/da/reports/backend/impl/VersionFinderImpl.java

The bestMatch should contains only exact matches of RH built artifacts -redhat-X .redhat-X

Fix pattern in version finder

---

cli/da-cli-admin.sh
cli/da-cli.sh
cli/listings.sh
cli/pretty-lookup.py

1. Rename `pom` option to `pom-bw` for `da-cli.sh` and `da-cli-admin.sh`
2. Add the `pom-report` option
3. Make `pretty-lookup.py` accept either a JSON list or a JSON object
The JSON object is returned for the `/reports/gav` endpoint, and the
JSON list returned for the `/reports/lookup` endpoint. As such, this
commit removes the '[' and ']' surrounding the JSON received in the
`report` function in `listings.sh`, since `pretty-lookup.py` can now
parse a JSON object too.
4. Make `pretty-lookup.py` search for the `message` key, which indicates
that something went wrong. If the `message` key is found,
print the `message` value and exit.
Note: this assumption is weak and should be improved in the future.
Note2: this change is required to properly handle the new response code
in the endpoints. …

[DA-93] Add pom-report option

---

cli/da-cli-admin.sh
cli/da-cli.sh
cli/listings.sh

1. Change the `pom-report` and `pom-bw` default behaviour. Now it'll only show top-level dependencies. The user can optionally select to show transitive dependencies by using the `--transitive` flag. (DA-98)
2. User can now optionally specify the directory to where the `pom.xml` to be analyzed is located for `pom-report` and `pom-bw`. (DA-101)

[DA-98][DA-101] CLI changes

---

application/src/main/application/META-INF/persistence.xml

Changes required in JBoss EAP 6.4:
1. Create a new PostgreSQL database called `da`
```bash
createdb da
```
2. In `jboss-eap-6.4/standalone/configuration/standalone.xml`:
- Add a new datasource:
```xml
<datasource jndi-name="java:jboss/datasources/PostgresDA" pool-name="PostgresDA" enabled="true">
<connection-url>jdbc:postgresql://localhost:5432/da</connection-url>
<driver>postgresql-jdbc4</driver>
<security>
<user-name>sa</user-name>
<password>sa</password>
</security>
</datasource>
```
Please change the username and password to something more appropriate.
- Add the JDBC PostgreSQL driver definition:
```xml
<driver name="postgresql-jdbc4" module="org.postgresql">
<driver-class>org.postgresql.Driver</driver-class>
</driver>
```
3. In …

[DA-107] Change datastore to PostgreSQL

---

communication/src/main/java/org/jboss/da/communication/pnc/api/PNCConnector.java
communication/src/main/java/org/jboss/da/communication/pnc/impl/PNCConnectorImpl.java
communication/src/main/java/org/jboss/da/communication/pnc/model/BuildConfiguration.java
communication/src/main/java/org/jboss/da/communication/pnc/model/BuildConfigurationCreate.java
communication/src/test/java/org/jboss/da/communication/PNCConnectorImplTest.java

Add 'Create Build Configuration' functionality to PNCConnector class.
When POSTing data about a new Build Configuration to PNC, the latter
requires us to not specify the id. As such, the `BuildConfiguration`
class was refactored so that `BuildConfigurationCreate` has all the
fields that in a BuildConfiguration minus the id.
`BuildConfiguration` then extends `BuildConfigurationCreate` and adds
the `id` field.
The three required fields for `BuildConfigurationCreate` for the
creation of Build Configurations to succeed are:
- name
- projectId
- environmentId
These three fields are annotated as `@NonNull`.

[DA-65] Implement create build configuration from PNC

---

common/pom.xml
common/src/main/java/org/jboss/da/common/util/Configuration.java
communication/pom.xml
communication/src/test/java/org/jboss/da/communication/model/GAVIntegrationTest.java
pom.xml
reports-rest/pom.xml
reports-rest/src/main/java/org/jboss/da/rest/reports/Reports.java
reports-rest/src/main/java/org/jboss/da/rest/reports/model/LookupReport.java

Fixes: 
- DA-117: pom.xml has dependencies on jackson deps with different versions
- DA-118: /lookup/gav endpoint has duplicate groupid, artifactId, and version fields in the JSON reply
- Use '206' for partial content instead of `Status.PARTIAL_CONTENT` since `Status.PARTIAL_CONTENT` is not defined in EAP 6.4.

REST fixes

---

cli/listings.sh
reports-rest/src/main/java/org/jboss/da/rest/reports/Reports.java

Since the '/lookup/gav' endpoint accepts several 'gavs', the endpoint
name should be changed to '/lookup/gavs' to reflect that it can accept
several 'gavs'.
Thanks to Nick Cross (@rnc) for proposing that idea!

[DA-119] Rename /lookup/gav endpoint to /lookup/gavs

---

reports-rest/src/main/java/org/jboss/da/rest/listings/Artifacts.java

Added '404' response code for endpoint '/listings/whitelist/gav' and
'/listings/blacklist/gav' in case the artifact queried is not present.
@jbartece @janinko @jomrazek Do you guys think this is enough or I should add more response codes for the other endpoints as well?

[DA-94] Add proper response code for listings endpoint

---

communication/src/main/java/org/jboss/da/communication/aprox/NoGAVInRepositoryException.java
communication/src/main/java/org/jboss/da/communication/aprox/api/AproxConnector.java
communication/src/main/java/org/jboss/da/communication/aprox/impl/AproxConnectorImpl.java
reports-backend/src/main/java/org/jboss/da/reports/api/ArtifactReport.java
reports-backend/src/main/java/org/jboss/da/reports/api/ReportsGenerator.java
reports-backend/src/main/java/org/jboss/da/reports/api/VersionLookupResult.java
reports-backend/src/main/java/org/jboss/da/reports/backend/api/DependencyTreeGenerator.java
reports-backend/src/main/java/org/jboss/da/reports/backend/api/VersionFinder.java
reports-backend/src/main/java/org/jboss/da/reports/backend/impl/DependencyTreeGeneratorImpl.java
reports-backend/src/main/java/org/jboss/da/reports/backend/impl/VersionFinderImpl.java
reports-backend/src/main/java/org/jboss/da/reports/impl/ReportsGeneratorImpl.java
reports-backend/src/test/java/org/jboss/da/reports/api/ArtifactReportTest.java
reports-backend/src/test/java/org/jboss/da/reports/backend/impl/VersionFinderTest.java
reports-backend/src/test/java/org/jboss/da/reports/impl/ReportsGeneratorImplTest.java
reports-rest/src/main/java/org/jboss/da/rest/reports/Reports.java
testsuite/src/test/java/org/jboss/da/test/server/communication/AproxTest.java

Optional is used at these places:
Instead of NoGAVInRepositoryException
AproxConnector returns Optional of GAVDependencyTree instead of
throwing NoGAVInRepositoryException.
Instead of null in Best match version
Where best match version was used passed or stored, Optional is
used - from VersionFinder, in VersionLookupResult and in
ArtifactReport.
In REST model (LookupReport and Report) null is still possible
beacuse of mapping into JSON.
Instead of null from ReportsGenerator
ReportsGenerator returns Optional of ArtifactReport instead of null.
When no versions are found for a GA it means that there are no built
versions for that GA, so we don't have to handle it in special way.
Where null was returned beacause of missing GA, empty list is now
returned.
This have the implication that …

Get rid of null and NoGAVInRepositoryException

---

cli/listings.sh
cli/pretty.py
reports-backend/src/main/java/org/jboss/da/listings/api/dao/WhiteArtifactDAO.java
reports-backend/src/main/java/org/jboss/da/listings/api/service/ArtifactService.java
reports-backend/src/main/java/org/jboss/da/listings/api/service/BlackArtifactService.java
reports-backend/src/main/java/org/jboss/da/listings/api/service/WhiteArtifactService.java
reports-backend/src/main/java/org/jboss/da/listings/impl/dao/WhiteArtifactDAOImpl.java
reports-backend/src/main/java/org/jboss/da/listings/impl/service/ArtifactServiceImpl.java
reports-backend/src/main/java/org/jboss/da/listings/impl/service/BlackArtifactServiceImpl.java
reports-backend/src/main/java/org/jboss/da/listings/impl/service/WhiteArtifactServiceImpl.java
reports-backend/src/main/java/org/jboss/da/reports/backend/impl/VersionFinderImpl.java
reports-rest/src/main/java/org/jboss/da/rest/listings/Artifacts.java
reports-rest/src/main/java/org/jboss/da/rest/listings/RestConvert.java
reports-rest/src/main/java/org/jboss/da/rest/listings/model/ContainsResponse.java

In Whitelist we now allow only redhat versions of artifacts.
If non-redhat version is being added, error 400 is returned.
If redhat version is being checked, exact match is searched.
If non-redhat version is being checked, it is converted to OSGi
version and then all redhad version of this artifact are searched.
In Blacklist we now store non-redhat OSGi versions of artifact.
If redhat version is being added, the redhat suffix is stripped and
then converted to OSGi.
If non-redhat version is being added, it is converted to OSGi version.
If redhat version is being checked, the redhat suffix is stripped and
then converted to OSGi.
If non-redhat version is being checked, it is converted to OSGi version.
This version returns list (empty or with one artifact) when checking if artifact is in …

Rework B&W list so it is easier for user to use it - LIST version

---

common/src/main/java/org/jboss/da/common/version/OSGiVersionParser.java
reports-backend/src/main/java/org/jboss/da/listings/impl/dao/GenericDAOImpl.java
reports-backend/src/main/java/org/jboss/da/listings/impl/service/ArtifactServiceImpl.java
reports-backend/src/main/java/org/jboss/da/listings/impl/service/BlackArtifactServiceImpl.java
reports-backend/src/main/java/org/jboss/da/listings/impl/service/WhiteArtifactServiceImpl.java

If the exception in Stateless bean is thrown than it is wrapped with the EJB exception.
The CDI beans don't do this.

Fix White/Black list services bug caused by Stateless beans

---

source-code-manager/src/main/resources/META-INF/beans.xml

This is apparently required to get Weld to inject the `SCM` object to other classes.

Add beans.xml to source-code-manager module

---

communication/src/main/java/org/jboss/da/communication/aprox/impl/AproxConnectorImpl.java

Very recently Aprox started to give us more dependencies for a GAV than
it should, hence creating a failure in our AproxTest. It turns out that
some things have changed in Aprox, and this change is required to make
Aprox give back the correct list of dependencies for a GAV. The fix is
inspired from the `Gist.java` found here:
https://github.com/Commonjava/aprox-stack-examples/blob/master/aprox/aprox-depgraph-examples/src/main/java/org/commonjava/aprox/ex/Gist.java

Fix AproxRemoteTest

---

reports-backend/src/main/java/org/jboss/da/reports/impl/ReportsGeneratorImpl.java
reports-backend/src/test/java/org/jboss/da/reports/impl/ReportsGeneratorImplTest.java

The fix is actually not really a fix.
The `GAVDependencyTree` generated is a huge tree where checking if a
cycle happened through its dependencies can be problematic and time
consuming.
Instead, the fix involves keeping a set of `GAVDependencyTree` nodes
already visited once it has been processed in `ReportsGenerator`. This
then allows us to:
- display the GAV and its dependencies the first time it is encountered
- only display the GAV the other subsequent times it is encountered.
This has the effect of:
1. Not getting the `ReportsGenerator` stuck in an infinite loop because
of cycles in `GAVDependencyTree`
2. Produce skinner reports since we now don't show the dependencies for
a GAV everytime it in encountered while generating the report, we
only show it once.

[DA-132] Fix for cycle in dependency tree

---

cli/listings.sh

Some projects' dependencies cannot be analyzed using the 'da-cli.sh'
script (for pom-bw and pom-report) because the `mvn dependency:list`
command fails.
This typically happens when we are missing an artifact which only gets
produced during the package phase.
The fix is to capture the failure and recommend the user to run `mvn
clean install` before running the 'da-cli.sh' script again.

[DA-145][DA-148] Fix for projects analysis with cli

---

communication/src/main/java/org/jboss/da/communication/pnc/api/PNCConnector.java
communication/src/main/java/org/jboss/da/communication/pnc/authentication/PNCAuthentication.java
communication/src/main/java/org/jboss/da/communication/pnc/authentication/PncAuthenticated.java
communication/src/main/java/org/jboss/da/communication/pnc/authentication/PncAuthenticationInterceptor.java
communication/src/main/java/org/jboss/da/communication/pnc/impl/AuthenticationException.java
communication/src/main/java/org/jboss/da/communication/pnc/impl/PNCConnectorImpl.java
communication/src/main/java/org/jboss/da/communication/pnc/model/Project.java
communication/src/main/resources/META-INF/beans.xml
communication/src/test/java/org/jboss/da/communication/PNCConnectorImplTest.java
testsuite/src/test/java/org/jboss/da/test/server/communication/PncRemoteTest.java
testsuite/src/test/resources/META-INF/beans.xml

New interceptor is created, which solves the situation, when access token expired. When it happens,
it triggers reauthentication and force reexecution of the called method in PNC connector
PNCAuthentication class was reworked to be a bean
Integration test for PNCConnector was created
Beans.xml file in communication was fixed to support interceptors

[DA-72]: Solve reauthentication to Keycloak, when token expires

---

bc-backend/src/main/java/org/jboss/da/bc/backend/api/POMInfoGenerator.java
bc-backend/src/main/java/org/jboss/da/bc/backend/impl/POMInfoGeneratorImpl.java
bc-backend/src/main/java/org/jboss/da/bc/impl/BuildConfigurationGeneratorImpl.java
bc-backend/src/main/java/org/jboss/da/bc/impl/ProjectHiearchyCreator.java
communication/src/main/java/org/jboss/da/communication/pom/PomAnalyzerImpl.java
communication/src/main/java/org/jboss/da/communication/pom/api/PomAnalyzer.java
communication/src/main/java/org/jboss/da/communication/scm/api/SCMConnector.java
communication/src/main/java/org/jboss/da/communication/scm/impl/SCMConnectorImpl.java

When there is log.warn in ProjectHiearchyCreator we can add some functionality in the future to propagate these errors into frontend
```
entity.addError("it doesn't work!");
```

Refactor BuildConfigurationGeneratorImpl into ProjectHiearchyCreator

---

communication/src/main/java/org/jboss/da/communication/scm/impl/SCMConnectorImpl.java
testsuite/src/test/java/org/jboss/da/test/server/scm/SCMTest.java

Given that we are not supporting svn cloning right now, disable svn
tests for now.
We are also disabling it because from time to time the test fails for no
apparent reason. Reducing the amount of noise in our testsuite will be
beneficial.

Disable SVN test

---

communication/pom.xml
communication/src/main/java/org/jboss/da/communication/CartographerProducer.java
communication/src/main/java/org/jboss/da/communication/pom/qualifier/DACartographerCore.java
pom.xml
testsuite/src/test/java/org/jboss/da/test/client/rest/reports/BugReporoducerRemoteTest.java

Galley in version 0.10.3 fixed issue with NPE.
We had to bump also version of cartographer and add galley-cdi-embedder
so there are no missing or ambiguous dependencies.

[DA-179] bump versions of galley and cartographer

---

communication/src/main/java/org/jboss/da/communication/aprox/FindGAVDependencyException.java
communication/src/main/java/org/jboss/da/communication/aprox/api/AproxConnector.java
communication/src/main/java/org/jboss/da/communication/aprox/impl/AproxConnectorImpl.java
reports-backend/src/main/java/org/jboss/da/reports/backend/impl/DependencyTreeGeneratorImpl.java
reports-backend/src/test/java/org/jboss/da/reports/impl/ReportsGeneratorImplTest.java
testsuite/src/test/java/org/jboss/da/test/client/rest/reports/RestApiReportsRemoteTest.java
testsuite/src/test/java/org/jboss/da/test/server/communication/AproxRemoteTest.java

Previously, when we asked Aprox to analyze a GAV for its dependencies,
we received the same result whether the GAV was:
- not present in Aprox and therefore cannot be analyzed
- present in Aprox and having no compile dependencies.
This commit fixes it by first checking if Aprox has the requested GAV in
its public repository. If yes, then proceed to the actual analysis.
However if the GAV is not in the public repository, a
`FindGAVDependencyException` is thrown.
Right now the `DependencyTreeGeneratorImpl` just catches the new
exception and returns an `Optional.empty()`. This will be really fixed
in DA-170 in another commit.
The JUnit tests are also adjusted to test/adapt for the new behaviour.

[DA-171] Know if Aprox can analyze a GAV or not.

---

cli/da-cli-admin.sh
cli/da-cli.sh
cli/listings.sh
cli/testsuite.py

This generation will only happen for black and white list files. The file created will be named 'junit.xml'
To run:
```
<path>/da-cli.sh pom-bw-junit-xml <path of maven repo>
```
Blacklisted GAV will be marked as a failed test. Not listed GAV are assumed to be successful tests.
Whitelisted GAVs are considered successful tests.
Maybe this generation will be enabled for other reports, as required.
Note: This gif, and webpage, was generated using the 'junit-viewer' npm library, by feeding on the junit.xml file generated. This particular testsuite was run on the pnc project.

[DA-152] Add option to generate JUnit XML file

---

bc-backend/src/main/java/org/jboss/da/bc/backend/impl/FinalizerImpl.java
bc-backend/src/main/java/org/jboss/da/bc/impl/BuildConfigurationGeneratorImpl.java
bc-backend/src/main/java/org/jboss/da/bc/impl/ProjectHiearchyCreator.java
bc-backend/src/main/java/org/jboss/da/bc/model/DependencyAnalysisStatus.java
bc-backend/src/main/java/org/jboss/da/bc/model/ProjectHiearchy.java
bc-rest/src/main/java/org/jboss/da/bc/BuildConfigurationsProduct.java
bc-rest/src/main/java/org/jboss/da/bc/model/BuildConfiguration.java
reports-backend/src/main/java/org/jboss/da/reports/api/ReportsGenerator.java
reports-backend/src/main/java/org/jboss/da/reports/backend/api/DependencyTreeGenerator.java
reports-backend/src/main/java/org/jboss/da/reports/backend/impl/DependencyTreeGeneratorImpl.java
reports-backend/src/main/java/org/jboss/da/reports/impl/ReportsGeneratorImpl.java
reports-backend/src/test/java/org/jboss/da/reports/impl/ReportsGeneratorImplTest.java
reports-rest/src/main/java/org/jboss/da/rest/reports/Reports.java

When using the bcg endpoint to analyze dependencies, it would be nice to
also get a status of how the dependencies went. Did the analysis
succeeded, failed, or has not been done yet?
In the longer term, this status field could be used in PNC UI to throw
relevant notifications to the user.
This commit builds on DA-171 which adds a way to know if Aprox could not
analyse a particular GAV. DA-171 is required to know whether the
analysis of the GAV failed, or the GAV had no dependencies. Previously
the two cases mentioned above could not be distinguished.
We add the status field by first creating an enum
(`DependencyAnalysisStatus`), and adding the status field to the backend
DAO `ProjectHierarchy` and the frontend DAO `BuildConfiguration`.
Most of the other changes occur in …

[DA-170] Status field for bcg endpoint

---

bc-backend/src/main/java/org/jboss/da/bc/backend/api/BCSetGenerator.java
bc-backend/src/main/java/org/jboss/da/bc/backend/impl/BCSetGeneratorImpl.java
bc-backend/src/main/java/org/jboss/da/bc/backend/impl/FinalizerImpl.java
communication/src/main/java/org/jboss/da/communication/pnc/api/PNCConnector.java
communication/src/main/java/org/jboss/da/communication/pnc/impl/PNCConnectorImpl.java

DA-167: Check if the product version already exists. If it does not,
create a new one. If it does, re-use the existing one.
DA-169: Check if the BuildConfigurationSet we are trying to use already
exists. If yes, then throw an error since we assume that the
BuildConfigurationSet we are going to use hasn't been created
yet.
The error thrown is `PNCRequestException`.
Note: I didn't write any tests since it's pretty hard to write tests that won't easily break as the BuildConfigurations/BuildConfigurationSet/Product/ProductVersion of the PNC server we'll test with change.

[DA-167][DA-169] Behaviour on existing PNC entities

---

reports-backend/src/main/java/org/jboss/da/reports/api/AdvancedArtifactReport.java
reports-backend/src/main/java/org/jboss/da/reports/api/ReportsGenerator.java
reports-backend/src/main/java/org/jboss/da/reports/impl/ReportsGeneratorImpl.java
reports-rest/src/main/java/org/jboss/da/rest/reports/Reports.java
reports-rest/src/main/java/org/jboss/da/rest/reports/model/AdvancedReport.java

REST endpoint is `/reports/scm-advanced`
Behaviour
=========
The new report should be based on the current SCM report and provide
this information:
- whitelisted artifacts
- blacklisted artifacts
- community GAV's, which has bestMatchVersion match community GAV's,
- community GAV's, which has no bestMatchVersion, but have built
versions of the same GA + if there are whitelisted versions of this
GA, add them there too
- community GAV's
- The same tree of dependencies as in the SCM report
Note: community === non RH artifacts
Note2: we only add the dependency to the
`communityGavsWithBestMatchVersions`, same for builtVersions +
whitelisted.
It looks something like this:
```json
{
"report": {the same report as /reports/scm},
"blacklistedArtifacts": [],
"whitelistedArtifacts": [], …
```

[DA-204] advanced scm report (based on comments)

---

reports-backend/src/main/java/org/jboss/da/reports/api/AdvancedArtifactReport.java
reports-backend/src/main/java/org/jboss/da/reports/impl/ReportsGeneratorImpl.java
reports-rest/src/main/java/org/jboss/da/rest/reports/Reports.java
reports-rest/src/main/java/org/jboss/da/rest/reports/model/AdvancedReport.java

Everywhere in the codebase we refer to artifacts as either being
'whitelisted' or 'blacklisted'. This commit makes the adavnced scm
report consistent with that convention by renaming:
- 'whitelistArtifact' to 'whitelistedArtifact'
- 'blacklistArtifact' to 'blacklistedArtifact'

Rename some fields in the advanced scm report

---

cli/da-cli-script.py

Delete whitelist-product method in cli requires support status, when it
is not in cli help nor needed by the endpoint.
This commit removes the requirement for status, making it consistent
with the documentation.

[DA-222] [master branch] CLI delete whitelist-product fix

---

bc-rest/pom.xml
bc-rest/src/main/webapp/WEB-INF/web.xml
bc-rest/src/main/webapp/doc/index.html
common/pom.xml
common/src/main/java/org/jboss/da/common/Constants.java
common/src/main/templates/org/jboss/da/common/Constants.java
pom.xml
reports-rest/pom.xml
reports-rest/src/main/java/org/jboss/da/rest/Root.java
reports-rest/src/main/webapp/WEB-INF/web.xml
reports-rest/src/main/webapp/doc/index.html
testsuite/src/test/java/org/jboss/da/test/client/rest/RestApiIndexTest.java
testsuite/src/test/rest/v-1.0/expectedResponse/index.html

I can't find out right settings of resource plugin to filter testsuite/src/test/rest/v-1.0/expectedResponse/index.html - i will look at it
I created https://docs.engineering.redhat.com/display/JP/Changing+of+REST+API+version so you know all places where you currently need to change version. We're using constants in app and these constants are used in annotations so I think the best state we can get is changing rest versions on 2 places in constants(for app) and in parent pom(for filter) 
If you know how to read property to annotation let me know.

[DA-228] Remove hardcoded application version, add property loading 

---

bc-backend/src/main/java/org/jboss/da/bc/api/ProductBuildConfigurationGenerator.java
bc-backend/src/main/java/org/jboss/da/bc/api/ProjectBuildConfigurationGenerator.java
bc-backend/src/main/java/org/jboss/da/bc/backend/api/BCSetGenerator.java
bc-backend/src/main/java/org/jboss/da/bc/backend/api/Finalizer.java
bc-backend/src/main/java/org/jboss/da/bc/backend/impl/BCSetGeneratorImpl.java
bc-backend/src/main/java/org/jboss/da/bc/backend/impl/FinalizerImpl.java
bc-backend/src/main/java/org/jboss/da/bc/impl/BuildConfigurationGeneratorImpl.java
bc-backend/src/main/java/org/jboss/da/bc/model/GeneratorEntity.java
bc-backend/src/main/java/org/jboss/da/bc/model/ProductGeneratorEntity.java
bc-backend/src/main/java/org/jboss/da/bc/model/ProjectGeneratorEntity.java
bc-backend/src/test/java/org/jboss/da/bc/backend/impl/BuildConfigurationGeneratorImplTest.java
bc-rest/src/main/java/org/jboss/da/bc/BuildConfigurationsProduct.java
bc-rest/src/main/java/org/jboss/da/bc/BuildConfigurationsProject.java
bc-rest/src/main/java/org/jboss/da/bc/BuildConfigurationsREST.java
bc-rest/src/main/java/org/jboss/da/bc/model/EntryEntity.java
bc-rest/src/main/java/org/jboss/da/bc/model/InfoEntity.java
testsuite/src/test/rest/v-1.0/expectedResponse/build-configuration/generate/product/analyse-next-level/da-application-1.json
testsuite/src/test/rest/v-1.0/expectedResponse/build-configuration/generate/product/analyse-next-level/da-common-1.json
testsuite/src/test/rest/v-1.0/expectedResponse/build-configuration/generate/product/start-process/da-common.json
testsuite/src/test/rest/v-1.0/expectedResponse/build-configuration/generate/product/start-process/da-parent.json
testsuite/src/test/rest/v-1.0/request/build-configuration/generate/product/analyse-next-level/da-application-1.json
testsuite/src/test/rest/v-1.0/request/build-configuration/generate/product/analyse-next-level/da-common-1.json
testsuite/src/test/rest/v-1.0/request/build-configuration/generate/product/finish-process/da-parent.json
testsuite/src/test/rest/v-1.0/request/build-configuration/generate/product/start-process/da-common.json
testsuite/src/test/rest/v-1.0/request/build-configuration/generate/product/start-process/da-parent.json

Instead of trying to create a product, we'll just assume that the
product already exists.
The REST call to the import endpoint doesn't change though. We'll still
have to send the product name.
We'll still try to create a product version if it hasn't been created
yet.

[DA-192] Move creating of products to UI in Product Import

---

communication/src/main/java/org/jboss/da/communication/pnc/impl/PNCConnectorImpl.java

If an error occurs, an exception is thrown, that entity was already read

Fix uncorrected checking for missing entity.

---

communication/src/main/java/org/jboss/da/communication/aprox/model/GAVDependencyTree.java
communication/src/main/java/org/jboss/da/communication/pom/GalleyWrapper.java
communication/src/main/java/org/jboss/da/communication/pom/LocalRepo.java
communication/src/main/java/org/jboss/da/communication/pom/PomAnalyzerImpl.java
communication/src/main/java/org/jboss/da/communication/pom/api/PomAnalyzer.java
communication/src/main/java/org/jboss/da/communication/pom/impl/DependencyTreeBuilder.java
communication/src/main/java/org/jboss/da/communication/scm/api/SCMConnector.java
communication/src/main/java/org/jboss/da/communication/scm/impl/SCMConnectorImpl.java
reports-backend/src/main/java/org/jboss/da/listings/impl/service/WLFillerImpl.java
reports-backend/src/main/java/org/jboss/da/reports/backend/impl/DependencyTreeGeneratorImpl.java
testsuite/src/test/java/org/jboss/da/test/server/communication/GalleyWrapperTest.java
testsuite/src/test/rest/v-1.0/expectedResponse/reports/scm/dependency-analysis.json

Some functionality from PomAnalyzerImpl was trasnfered into GalleyWrapper.
Construction of DependencyTree was recreated and split into DependencyTreeBuilder.
Dependency on SCM was removed (SCM operation should be handled by caller methods).

Refactor PomAnalyzerImpl and fix [DA-239] 

---

communication/src/main/java/org/jboss/da/communication/pnc/model/BuildConfigurationCreate.java
testsuite/src/test/java/org/jboss/da/test/server/communication/PncRemoteTest.java

The BuildConfiguration JSON object provided by PNC for creating new BuildConfiguration has changed.
The productVersionId and scmRepoUrl fields have become mandatory, and we can only associate a buildConfiguration with only one productVersion. This change is required for #274 to pass its testsuite.

Refactor BC object for PNC >= 0.9

---

communication/src/main/java/org/jboss/da/communication/pom/LocalRepo.java

When there are several pomfiles in SCM repository with the same GAV,
there is FileAlreadyExistsException when creating LocalRepo pom cache.
This is usually harmless, as it happens only when there are pom files
e.g. in tests.

Workaround for FileAlreadyExistsException in LocalRepo

---

testsuite/pom.xml

E.g. to exclude BugReporoducerRemoteTest use:
-Dtestsuite.test.excludes=**/BugReporoducerRemoteTest.java

Allow exclude test from commandline

---

common/src/main/java/org/jboss/da/common/json/DAConfig.java
common/src/main/resources/da-config.json
communication/src/main/java/org/jboss/da/communication/aprox/api/AproxConnector.java
communication/src/main/java/org/jboss/da/communication/aprox/impl/AproxConnectorImpl.java
communication/src/main/java/org/jboss/da/communication/pom/GalleyWrapper.java
communication/src/main/java/org/jboss/da/communication/pom/PomAnalyzerImpl.java

Use 'aproxGroup' repository for -redhat version finding.
Use 'aproxGroupPublic' for dependency search.

[NCL-2048] Use two repository groups

---

bc-backend/src/main/java/org/jboss/da/bc/backend/impl/FinalizerImpl.java
bc-backend/src/test/java/org/jboss/da/bc/backend/impl/FinalizerImplTest.java
communication/src/main/java/org/jboss/da/communication/pnc/api/PNCConnector.java
communication/src/main/java/org/jboss/da/communication/pnc/impl/PNCConnectorImpl.java
communication/src/main/java/org/jboss/da/communication/pnc/model/BuildConfigurationBPMCreate.java
testsuite/src/test/java/org/jboss/da/test/server/communication/PncRemoteTest.java

Because creating BuildConfigurations using BPM process doesn't return id
of the newly createted BuildConfiguration, we need to get the id in some
other way. For now we will poll PNC until the BC is created, in the
future we should use websockets to retrieve a notification about BC
being created.

Add workaround for getting id of new build configurations

---

reports-model/src/main/java/org/jboss/da/model/rest/GA.java
testsuite/src/test/rest/v-1/expectedResponse/build-configuration/generate/product/analyse-next-level/da-application-1.json

Although maven specification prohibits it, maven doesn't enfore it.
That means considerable amount of project with dash in groupId exists.

Relax GAV validation, allow dash in group id

---

cli-wrap/src/main/resources/cli/da_cli_script.py

With a leading space on the Authorization key, the requests library
doesn't like it and throws:
```
[pkocandr@vlk-ntb cli]$ ./da-cli.py add whitelist-product EAP:7.0.3 SUPPORTED
Using stored auth token.
Traceback (most recent call last):
File "./da-cli.py", line 423, in <module>
CLITool()
File "./da-cli.py", line 182, in __init__
getattr(self, args.command.replace("-","_"))()
File "./da-cli.py", line 191, in add
getattr(self, "add_"+args.color.replace("-","_"))()
File "./da-cli.py", line 311, in add_whitelist_product
self.listings.addWhitelistProd(sys.argv[3], sys.argv[4])
File "/home/petr/workspace/git/dependency-analysis/cli-wrap/src/main/resources/cli/listings.py", line 22, in addWhitelistProd
da_cli_script.add_artifacts(None, "whitelist-product", product, status)
File …
```

(version-1.2.x) Use correct auth header

---

cli-wrap/src/main/resources/cli/da_cli_script.py

With a leading space on the Authorization key, the requests library
doesn't like it and throws:
```
[pkocandr@vlk-ntb cli]$ ./da-cli.py add whitelist-product EAP:7.0.3 SUPPORTED
Using stored auth token.
Traceback (most recent call last):
File "./da-cli.py", line 423, in <module>
CLITool()
File "./da-cli.py", line 182, in __init__
getattr(self, args.command.replace("-","_"))()
File "./da-cli.py", line 191, in add
getattr(self, "add_"+args.color.replace("-","_"))()
File "./da-cli.py", line 311, in add_whitelist_product
self.listings.addWhitelistProd(sys.argv[3], sys.argv[4])
File "/home/petr/workspace/git/dependency-analysis/cli-wrap/src/main/resources/cli/listings.py", line 22, in addWhitelistProd
da_cli_script.add_artifacts(None, "whitelist-product", product, status)
File …
```

Use correct auth header

---

communication/src/main/java/org/jboss/da/communication/aprox/impl/AproxConnectorImpl.java
reports-backend/src/main/java/org/jboss/da/reports/impl/ReportsGeneratorImpl.java
reports-backend/src/test/java/org/jboss/da/reports/impl/ReportsGeneratorImplTest.java
reports-model/src/main/java/org/jboss/da/reports/model/rest/LookupGAVsRequest.java
reports-rest/src/main/java/org/jboss/da/rest/reports/Reports.java

This PR is related to #447, applying changes based on Honza's comments in the PR.
* The last 4 commits in #447 has been squashed.
* The test was rewritten to explicitly list the unique GAVs we are expecting, instead on relying on `HashSet` to find unique GAVs (this might get broken if `hashCode` and `equals` implementation in the `GAV` class is broken)

Rework requests to Indy in lookup/gavs not to be duplicated for the same GA - master

---

communication/src/main/java/org/jboss/da/communication/aprox/impl/AproxConnectorImpl.java
reports-backend/src/main/java/org/jboss/da/reports/impl/ReportsGeneratorImpl.java
reports-backend/src/test/java/org/jboss/da/reports/impl/ReportsGeneratorImplTest.java
reports-model/src/main/java/org/jboss/da/reports/model/rest/LookupGAVsRequest.java
reports-rest/src/main/java/org/jboss/da/rest/reports/Reports.java

This PR is related to #448, applying changes based on Honza's comments in the PR.
* The last 4 commits in #448  has been squashed.
* The test was rewritten to explicitly list the unique GAVs we are expecting, instead on relying on `HashSet` to find unique GAVs (this might get broken if `hashCode` and `equals` implementation in the `GAV` class is broken)

Rework requests to Indy in lookup/gavs not to be duplicated for the same GA - 1.2

---

communication/src/main/java/org/jboss/da/communication/aprox/impl/AproxConnectorImpl.java

This commit also adds a retry for HTTP status 500 from Indy when
fetching the maven-metadata.xml file. This is in addition to the current
logic which is to retry on HTTP status 504.
This is done as Indy sometimes recovers from HTTP status 500 errors to
provide us with the right content (See NOS-1155).
This commit also adds a waiting time between retries; with the waiting
time determined by using an exponential backoff. This will hopefully
help the network/Indy recover from overload and provide the correct data
at a later time.

[NCL-3604][v1.2] Add retry for status 500 from Indy

---

communication/src/main/java/org/jboss/da/communication/aprox/impl/AproxConnectorImpl.java

We had only ConnectTimeout set but that's only for initial socket
connection, we also need read timeout if we want to timeout when indy
takes a long time to respond.

[NCL-3465] Add read timeout when communicating with Indy

---

README.md
application/pom.xml
application/src/main/application/META-INF/application.xml
application/src/main/application/META-INF/jboss-deployment-structure.xml
communication/pom.xml
communication/src/main/java/org/jboss/da/communication/aprox/impl/AproxConnectorImpl.java
communication/src/test/java/org/jboss/da/communication/aprox/AproxConnectorTest.java
metrics/pom.xml
metrics/src/main/java/org/jboss/da/metrics/MetricsConfiguration.java
metrics/src/main/java/org/jboss/da/metrics/exceptions/NoPropertyException.java
pom.xml
reports-rest/pom.xml
reports-rest/src/main/java/org/jboss/da/rest/ReportsRestActivator.java
reports-rest/src/main/java/org/jboss/da/rest/metrics/GeneralRestMetricsFilter.java
reports-rest/src/main/java/org/jboss/da/rest/metrics/TimedMetric.java
reports-rest/src/main/java/org/jboss/da/rest/metrics/TimedMetricFilter.java
testsuite/pom.xml
testsuite/src/test/resources/META-INF/application.xml
testsuite/src/test/resources/META-INF/jboss-deployment-structure.xml

This PR adds:
- Metrics support via Dropwizard Metrics for JVM and in-app instrumentation
- Add all REST req/s and timer
- Add support to instrument particular REST method via `@TimedMetric`
- Add timer for Apox/Indy client

Add metrics support

---

common/src/main/java/org/jboss/da/common/version/VersionAnalyzer.java
common/src/main/java/org/jboss/da/common/version/VersionParser.java
common/src/test/java/org/jboss/da/common/version/VersionAnalyzerTest.java
common/src/test/java/org/jboss/da/common/version/VersionParserTest.java

When different version suffix is used, it's usead as additional (priority)
suffix, not as an override for the default one.
suffix: null
returned: redhat-1, redhat-2, ...
bestmatch: redhat-2
suffix: foo
returned: foo-1, redhat-1, redhat-2, ...
bestmatch: foo-1

[NCL-4079] When version suffix is provided, use both provided and default

---

common/src/main/java/org/jboss/da/common/version/VersionAnalyzer.java
common/src/test/java/org/jboss/da/common/version/VersionAnalyzerTest.java

In case where the list of available version contained versions with
non-default suffix but it was not matching* the query flag
onlyDefaultSuffixPresent fas falsy set to true.
* Example:
suffix: "temporary-redhat"
query: "1.0.0"
available: "1.0.0.redhat-1", "2.3.4.temporary-redhat-1"
NA

[NCL-4266] Fix order of filtering versions when finding Best Match

---

common/src/main/java/org/jboss/da/common/version/VersionParser.java
common/src/test/java/org/jboss/da/common/version/VersionParserTest.java
testsuite/src/test/java/org/jboss/da/test/client/rest/reports/BugReporoducerRemoteTestIT.java
testsuite/src/test/rest/v-1/expectedResponse/reports/lookup/gavs/NCLSUP132.json
testsuite/src/test/rest/v-1/request/reports/lookup/gavs/NCLSUP132.json

[NCLSUP-132] Allow dash instead of dot as separator before MICRO in version parser

---

pom.xml
reports-backend/src/main/java/org/jboss/da/reports/impl/ReportsGeneratorImpl.java
reports-model/pom.xml
reports-model/src/main/java/org/jboss/da/lookup/model/MavenLookupResult.java
reports-model/src/main/java/org/jboss/da/lookup/model/NPMLookupResult.java
reports-model/src/main/java/org/jboss/da/reports/model/response/LookupReport.java
reports-model/src/main/java/org/jboss/da/reports/model/response/NPMLookupReport.java
reports-model/src/test/java/org/jboss/da/reports/model/response/ReportTest.java
reports-model/src/test/resources/deserializeTest/mavenLookupReport.json
reports-model/src/test/resources/deserializeTest/mavenLookupResult.json
reports-model/src/test/resources/deserializeTest/npmLookupReport.json
reports-model/src/test/resources/deserializeTest/npmLookupResult.json

This change applies to:
- LookupReport
- NPMLookupReport
The changes are required to properly deserialize the JSON into the
objects for clients using the DTOs to deserialize.
While a few stuff were tried, it looks like Jackson is confused by the
combination of the 'Builder' pattern and '@JsonUnwrapped' annotation and
doesn't know what to do. To keep it simple, this commit removes the
`@Builder` annotation, and uses the 'NoArgsConstructor' to make sure
Jackson can deserialize properly.
Tests are written to make sure that the deserialization process works.

Changes to better deserialize JSON using the DTO

---

reports-rest/src/main/java/org/jboss/da/rest/JacksonProvider.java

This is used to properly serialize the Java 8 timestamps by Jackson. We use a similar thing in PNC-Orch

[NCL-6708] Provide a jackson instance loaded with timestamp module

---

reports-rest/src/main/java/org/jboss/da/rest/JacksonProvider.java

This is used to properly serialize the Java 8 timestamps by Jackson. We use a similar thing in PNC-Orch

[v2.6.x][NCL-6708] Provide a jackson instance loaded with timestamp module

---

reports-model/src/main/java/org/jboss/da/lookup/model/MavenLatestResult.java
reports-model/src/main/java/org/jboss/da/lookup/model/MavenLookupResult.java
reports-model/src/main/java/org/jboss/da/lookup/model/MavenResult.java
reports-model/src/main/java/org/jboss/da/lookup/model/MavenVersionsResult.java
reports-model/src/main/java/org/jboss/da/lookup/model/NPMLookupResult.java
reports-model/src/main/java/org/jboss/da/lookup/model/NPMResult.java
reports-model/src/main/java/org/jboss/da/lookup/model/NPMVersionsResult.java

This change should help to eliminate order methods for every result type in bacon https://github.com/project-ncl/bacon/blob/main/da/src/main/java/org/jboss/bacon/da/DaHelper.java#L203

Create super-classes for lookup results
